version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    command: ./docker-entrypoint.sh
    environment:
      APP_MODE: prod
      baseURL: http://103.118.47.131:8888
    ports:
      - 10000:3000
