version: '3'

services:

  web:
    image: registry.gitlab.com/startup-cambodia/web-public/development:latest
    command: ./docker-entrypoint.sh
    environment:
      APP_MODE: prod
      baseURL: http://core:8000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: startup-platform-networks